version: '3'

services:
  test-node:
    container_name: test-node
    image: "vcity/validator"
    environment:
      - MONIKER=test-node
      - KEY=user0
      - MNEMONIC=neither tent pull crush leave achieve jealous blood slush dumb claw furnace hill flight margin pattern theory biology relax celery odor pink rather ranch
    volumes:
      - ./share:/home/user/share
      - ./.vcity:/home/user/.vcity
    command: 
      - cp ./share/genesis.json ./genesis.json && cp ./share/start.sh ./start.sh && chmod +x ./start.sh && ./start.sh
      # - tail -f /dev/null
    ports:
      - "26656-26657:26656-26657"
      - "8545:8545"
      - "1317:1317"
      - "9091:9091"
    # command: cp ./share/genesis.json ./genesis.json && cp ./share/start.sh ./start.sh && chmod +x ./start.sh && ./start.sh
    restart: always
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:26657/status" ]
      interval: 30s
      timeout: 10s
      retries: 5